"""Qdrant vector repository for paper abstract embeddings.

Enables semantic search over biomedical literature — given a natural language
query, finds the most relevant papers by cosine similarity of embeddings
generated by sentence-transformers (all-MiniLM-L6-v2, 384 dimensions).
"""

import logging
import uuid
from typing import Any

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    PointStruct,
    VectorParams,
)

from drug_discovery.storage.base import VectorRepository

logger = logging.getLogger(__name__)

COLLECTION = "papers"
VECTOR_DIM = 384  # all-MiniLM-L6-v2 output dimension


class QdrantVectorRepository(VectorRepository):
    """Paper embedding repository backed by Qdrant.

    Creates the collection on first use if it does not exist.

    Args:
        url: Qdrant HTTP URL (e.g. 'http://localhost:6333').
    """

    def __init__(self, url: str) -> None:
        self._client = QdrantClient(url=url)
        self._ensure_collection()

    def _ensure_collection(self) -> None:
        """Create the papers collection if it does not already exist."""
        existing = [c.name for c in self._client.get_collections().collections]
        if COLLECTION not in existing:
            self._client.create_collection(
                collection_name=COLLECTION,
                vectors_config=VectorParams(size=VECTOR_DIM, distance=Distance.COSINE),
            )
            logger.info("qdrant: created collection '%s'", COLLECTION)

    async def upsert(
        self,
        pmid: str,
        embedding: list[float],
        payload: dict[str, Any],
    ) -> None:
        """Insert or update an embedding vector.

        Args:
            pmid: PubMed identifier — used as a stable point ID.
            embedding: Float vector of length VECTOR_DIM (384).
            payload: Metadata stored alongside the vector (title, year, journal).
        """
        if len(embedding) != VECTOR_DIM:
            raise ValueError(
                f"embedding must have {VECTOR_DIM} dimensions, got {len(embedding)}"
            )

        point_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"pubmed:{pmid}"))
        self._client.upsert(
            collection_name=COLLECTION,
            points=[PointStruct(id=point_id, vector=embedding, payload={"pmid": pmid, **payload})],
        )
        logger.debug("qdrant: upserted PMID %s (point_id=%s)", pmid, point_id)

    async def search(
        self,
        query_vector: list[float],
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """Find the nearest paper embeddings to a query vector.

        Args:
            query_vector: Encoded query of length VECTOR_DIM.
            limit: Maximum number of results to return.

        Returns:
            List of payload dicts sorted by descending similarity score,
            each containing at minimum 'pmid' and 'score'.
        """
        if len(query_vector) != VECTOR_DIM:
            raise ValueError(
                f"query vector must have {VECTOR_DIM} dimensions, got {len(query_vector)}"
            )

        hits = self._client.search(
            collection_name=COLLECTION,
            query_vector=query_vector,
            limit=limit,
        )
        return [{"score": hit.score, **(hit.payload or {})} for hit in hits]
